version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: gamify-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gamify
    volumes:
      - mongo-data:/data/db
    networks:
      - gamify-network

  mongo-express:
    image: mongo-express:latest
    container_name: gamify-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - gamify-network

volumes:
  mongo-data:

networks:
  gamify-network:
    driver: bridge

